-- Seed the words table from words.json. Run once in Supabase SQL Editor
-- AFTER running schema.sql. Safe to re-run, and safe to run again after
-- adding words (ON CONFLICT DO NOTHING inserts only the new ones).
insert into public.words (text, flies) values
('Bird', true),
('Crow', true),
('Sparrow', true),
('Pigeon', true),
('Parrot', true),
('Eagle', true),
('Owl', true),
('Hawk', true),
('Falcon', true),
('Vulture', true),
('Seagull', true),
('Swan', true),
('Duck', true),
('Stork', true),
('Flamingo', true),
('Woodpecker', true),
('Kingfisher', true),
('Hummingbird', true),
('Cuckoo', true),
('Dove', true),
('Pelican', true),
('Robin', true),
('Magpie', true),
('Goose', true),
('Heron', true),
('Raven', true),
('Myna', true),
('Bulbul', true),
('Nightingale', true),
('Lark', true),
('Swift', true),
('Canary', true),
('Toucan', true),
('Macaw', true),
('Cockatoo', true),
('Sunbird', true),
('Finch', true),
('Starling', true),
('Swallow', true),
('Goldfinch', true),
('Ibis', true),
('Egret', true),
('Oriole', true),
('Parakeet', true),
('Cormorant', true),
('Skylark', true),
('Butterfly', true),
('Bee', true),
('Bumblebee', true),
('Wasp', true),
('Hornet', true),
('Mosquito', true),
('Housefly', true),
('Moth', true),
('Dragonfly', true),
('Firefly', true),
('Bat', true),
('Locust', true),
('Ladybug', true),
('Cicada', true),
('Gnat', true),
('Airplane', true),
('Helicopter', true),
('Jet', true),
('Rocket', true),
('Drone', true),
('Hot Air Balloon', true),
('Spaceship', true),
('UFO', true),
('Glider', true),
('Kite', true),
('Balloon', true),
('Zeppelin', true),
('Blimp', true),
('Paraglider', true),
('Biplane', true),
('Seaplane', true),
('Fairy', true),
('Dragon', true),
('Angel', true),
('Superman', true),
('Iron Man', true),
('Peter Pan', true),
('Buzz Lightyear', true),
('Tinker Bell', true),
('Hedwig', true),
('Albatross', true),
('Condor', true),
('Osprey', true),
('Hornbill', true),
('Lovebird', true),
('Cockatiel', true),
('Budgie', true),
('Bee Eater', true),
('Fruit Fly', true),
('Horsefly', true),
('Hoverfly', true),
('Paper Plane', true),
('Frisbee', true),
('Boomerang', true),
('Arrow', true),
('Satellite', true),
('Fighter Jet', true),
('Parachute', true),
('Space Shuttle', true),
('Witch', true),
('Phoenix', true),
('Pegasus', true),
('Genie', true),
('Magic Carpet', true),
('Thor', true),
('Goku', true),
('Hanuman', true),
('Garuda', true),
('Dumbo', true),
('Doctor Strange', true),
('Elephant', false),
('Narendra Modi', false),
('Lion', false),
('Tiger', false),
('Cow', false),
('Dog', false),
('Cat', false),
('Horse', false),
('Goat', false),
('Sheep', false),
('Buffalo', false),
('Monkey', false),
('Donkey', false),
('Pig', false),
('Rabbit', false),
('Deer', false),
('Bear', false),
('Fox', false),
('Wolf', false),
('Camel', false),
('Giraffe', false),
('Zebra', false),
('Hippo', false),
('Rhino', false),
('Kangaroo', false),
('Squirrel', false),
('Cheetah', false),
('Leopard', false),
('Panther', false),
('Jaguar', false),
('Hyena', false),
('Bison', false),
('Panda', false),
('Koala', false),
('Sloth', false),
('Otter', false),
('Hedgehog', false),
('Porcupine', false),
('Hamster', false),
('Raccoon', false),
('Llama', false),
('Snake', false),
('Crocodile', false),
('Tortoise', false),
('Fish', false),
('Frog', false),
('Lizard', false),
('Earthworm', false),
('Rat', false),
('Snail', false),
('Crab', false),
('Octopus', false),
('Jellyfish', false),
('Starfish', false),
('Shark', false),
('Whale', false),
('Dolphin', false),
('Turtle', false),
('Chameleon', false),
('Cobra', false),
('Scorpion', false),
('Spider', false),
('Ant', false),
('Car', false),
('Bus', false),
('Truck', false),
('Train', false),
('Bicycle', false),
('Boat', false),
('Tractor', false),
('Scooter', false),
('Ship', false),
('Table', false),
('Chair', false),
('House', false),
('Tree', false),
('Stone', false),
('Book', false),
('Shoe', false),
('Fridge', false),
('Pikachu', false),
('Shrek', false),
('SpongeBob', false),
('Mickey Mouse', false),
('Jon Snow', false),
('Mowgli', false),
('Yak', false),
('Mule', false),
('Bull', false),
('Puppy', false),
('Kitten', false),
('Mongoose', false),
('Chipmunk', false),
('Beaver', false),
('Walrus', false),
('Seal', false),
('Platypus', false),
('Armadillo', false),
('Meerkat', false),
('Gorilla', false),
('Chimpanzee', false),
('Antelope', false),
('Toad', false),
('Centipede', false),
('Slug', false),
('Lobster', false),
('Auto Rickshaw', false),
('Bullock Cart', false),
('Submarine', false),
('Laptop', false),
('Mountain', false),
('Bridge', false),
('Chhota Bheem', false),
('Hulk', false),
('Baloo', false),
('Scooby Doo', false)
on conflict (text) do nothing;
