// Sound effects — plays the pre-baked WAVs in assets/sounds/
// (generated by scripts/generate-sounds.js, same recipes as the
// web app). Every call is wrapped so audio problems can never
// crash the game.

import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';

const SOURCES = {
  appear: require('../assets/sounds/appear.wav'),
  fly: require('../assets/sounds/fly.wav'),
  sit: require('../assets/sounds/sit.wav'),
  wrong: require('../assets/sounds/wrong.wav'),
  over: require('../assets/sounds/over.wav'),
  start: require('../assets/sounds/start.wav'),
  click: require('../assets/sounds/click.wav'),
};

const players = {};
let ready = false;

export async function initSfx() {
  try {
    await setAudioModeAsync({ playsInSilentMode: true });
    for (const [name, source] of Object.entries(SOURCES)) {
      players[name] = createAudioPlayer(source);
    }
    ready = true;
  } catch (e) {
    console.warn('sfx init failed (game continues silently):', e.message);
  }
}

export function play(name) {
  if (!ready) return;
  try {
    const p = players[name];
    if (!p) return;
    p.seekTo(0);
    p.play();
  } catch {
    // never let a sound stop the game
  }
}
